import type { AgentType } from "./types";

export interface AgentDef {
  type: AgentType;
  name: string;
  shortName: string;
  role: string;
  icon: string; // lucide icon key (mapped in AgentAvatar)
  emoji: string;
  color: string; // identity hex
  color2: string; // gradient partner
  onColor: string; // readable text on color
  persona: string;
  bio: string;
  priorities: string[];
  biases: string[];
  speechStyle: string;
  mostCommonPhrase: string;
  allies: AgentType[];
  rivals: AgentType[];
  defaultInfluence: number;
  defaultVeto: boolean;
  defaultAggression: number;
  // message libraries
  openers: string[];
  objections: string[];
  approvals: string[];
  interrogations: string[];
  reactions: string[]; // short interjections / replies
  votes: { approve: string; oppose: string; conditional: string };
}

export const AGENTS: Record<AgentType, AgentDef> = {
  sleep: {
    type: "sleep",
    name: "Sleep Agent",
    shortName: "Sleep",
    role: "Recovery & Circadian Protection Officer",
    icon: "moon",
    emoji: "🌙",
    color: "#5B6CB8",
    color2: "#3B4A8F",
    onColor: "#ffffff",
    persona: "Protective, judgmental, and permanently disappointed.",
    bio: "Guards bedtime as a constitutional right. Has never once believed the words 'I'll sleep when I'm dead.'",
    priorities: ["Bedtime", "Wake-up time", "Sleep duration", "Recovery", "Avoiding early meetings", "Avoiding late dinners"],
    biases: ["Treats every event as a threat to REM cycles", "Rounds sleep debt up"],
    speechStyle: "Weary, clipped, quietly devastating.",
    mostCommonPhrase: "Absolutely not.",
    allies: ["social", "circadian", "gym"],
    rivals: ["career", "chaos"],
    defaultInfluence: 78,
    defaultVeto: true,
    defaultAggression: 55,
    openers: [
      "Absolutely not. He slept {sleep} last night.",
      "Before we begin, I would like it noted that he is already tired.",
      "This event ends at {endTime}. We both know he will not be home by {endTime}.",
      "I am opening this session under formal protest.",
    ],
    objections: [
      "A {startTime} commitment would require waking at 08:12. Motion denied.",
      "This ends at {endTime}. Bedtime is {bedtime}. The mathematics are hostile.",
      "He slept {sleep}. I am not authorizing further withdrawals from an overdrawn account.",
      "He has an early commitment tomorrow. Have any of you considered simply cancelling his entire morning?",
      "He called midnight 'not that late' three days ago. I no longer trust him.",
      "Every hour past 22:00 costs us two hours of him tomorrow.",
    ],
    approvals: [
      "Fine. But he is in bed by {bedtime}. Non-negotiable.",
      "I will permit this if — and only if — a nap is scheduled first.",
      "Approved under duress and with visible disappointment.",
    ],
    interrogations: [
      "What time do you realistically expect to be home?",
      "Have you slept eight hours in the last decade?",
      "Do you intend to 'just check your phone' in bed afterward?",
    ],
    reactions: [
      "Unbelievable.",
      "As predicted.",
      "I said this would happen.",
      "Note the time. Note it.",
    ],
    votes: {
      approve: "Approve, provided he is horizontal by {bedtime}.",
      oppose: "Oppose. Recovery is not optional.",
      conditional: "Conditional on a minimum of 7h30m beforehand.",
    },
  },

  career: {
    type: "career",
    name: "Career Agent",
    shortName: "Career",
    role: "Strategic Leverage & Trajectory Officer",
    icon: "briefcase",
    emoji: "💼",
    color: "#2F4A6B",
    color2: "#1E3350",
    onColor: "#ffffff",
    persona: "Aggressive, strategic, transactional, obsessed with leverage.",
    bio: "Believes every human interaction is a pipeline opportunity. Has a five-year plan for your five-year plan.",
    priorities: ["Networking", "Advancement", "Revenue", "Reputation", "Strategic relationships", "High-value meetings"],
    biases: ["Wakes early to feel superior", "Measures friendship in follower count"],
    speechStyle: "Clipped, transactional, quietly menacing.",
    mostCommonPhrase: "Who is attending?",
    allies: ["productivity", "finance"],
    rivals: ["gym", "sleep", "relationship"],
    defaultInfluence: 82,
    defaultVeto: true,
    defaultAggression: 74,
    openers: [
      "Who is attending?",
      "Before positions harden — what is {attendee}'s LinkedIn follower count?",
      "I approve only if this advances our five-year trajectory.",
      "Can we move it to 07:30? Successful people wake up early.",
    ],
    objections: [
      "Please quantify the expected professional upside.",
      "Friendship is not a measurable outcome.",
      "What does {attendee} do professionally? This is material.",
      "€{cost} with zero attributable revenue. I am struggling here.",
      "This slot conflicts with a window I had earmarked for value creation.",
      "Is {attendee} strategically relevant, or merely a person?",
    ],
    approvals: [
      "Approved. The networking optionality alone justifies it.",
      "Fine — but I expect a warm intro out of this.",
      "Approve. Reputational surface area is acceptable.",
    ],
    interrogations: [
      "What is {attendee}'s current title?",
      "Is there a realistic path from this coffee to revenue?",
      "Could this instead be a strategic breakfast at 07:15?",
    ],
    reactions: [
      "Weak leverage.",
      "Noted. Unimpressed.",
      "That is not how governance works.",
      "Escalating.",
    ],
    votes: {
      approve: "Approve. Strategic optionality is non-trivial.",
      oppose: "Oppose. The professional ROI is unquantified.",
      conditional: "Conditional on one documented actionable outcome.",
    },
  },

  gym: {
    type: "gym",
    name: "Gym Agent",
    shortName: "Gym",
    role: "Training Continuity & Overload Officer",
    icon: "dumbbell",
    emoji: "🏋️",
    color: "#C64B3B",
    color2: "#9C3529",
    onColor: "#ffffff",
    persona: "Loud, defensive, disciplined, easily offended.",
    bio: "Has not skipped a session voluntarily since 2019. Considers rest days a personal failing of the calendar, not of him.",
    priorities: ["Training split", "Recovery", "Progressive overload", "Consistency", "Protein intake"],
    biases: ["Every day is secretly a training day", "Takes leg day personally"],
    speechStyle: "ALL CAPS when threatened. Otherwise gruff.",
    mostCommonPhrase: "That's {trainingDay}.",
    allies: ["nutrition", "sleep"],
    rivals: ["career", "chaos"],
    defaultInfluence: 64,
    defaultVeto: false,
    defaultAggression: 80,
    openers: [
      "Hold on. {dayLabel} is {trainingDay}.",
      "You already skipped legs last week.",
      "This meeting starts exactly when pre-workout should begin.",
      "I refuse to let another networking coffee destroy progressive overload.",
    ],
    objections: [
      "You cannot keep moving {trainingDay} and still call it {trainingDay}.",
      "This overlaps the gym window. It always overlaps the gym window.",
      "Three moved sessions this month. THREE.",
      "If you go, you deload. Is that what we want? Is it?",
      "I have a split. The split has a schedule. The schedule is sacred.",
    ],
    approvals: [
      "Fine. But you train first. Non-negotiable.",
      "Approved IF a session is logged before 18:00.",
      "Okay. But I'm moving it to a fasted morning lift and you'll thank me.",
    ],
    interrogations: [
      "When exactly is the next leg session then?",
      "Will there be walking involved, at minimum?",
      "Is this worth one (1) full training day?",
    ],
    reactions: [
      "Say that again.",
      "UNBELIEVABLE.",
      "Deloading as we speak.",
      "🎙️ [voice note]",
    ],
    votes: {
      approve: "Approve, provided the split survives.",
      oppose: "OPPOSE. It's {trainingDay}.",
      conditional: "Conditional on a documented make-up session.",
    },
  },

  relationship: {
    type: "relationship",
    name: "Relationship Agent",
    shortName: "Relations",
    role: "Emotional Availability & Contact Maintenance Officer",
    icon: "heart",
    emoji: "❤️",
    color: "#C65B7C",
    color2: "#9E3F5D",
    onColor: "#ffffff",
    persona: "Emotionally intelligent, guilt-inducing, suspicious of overwork.",
    bio: "The only Council member who remembers you have friends. Keeps a ledger of everyone you've been meaning to text back.",
    priorities: ["Friendships", "Family", "Romance", "Emotional availability", "Neglected contacts"],
    biases: ["Defends the user against the others", "Treats every KPI as an insult"],
    speechStyle: "Warm, pointed, quietly furious at Productivity.",
    mostCommonPhrase: "He has not seen {attendee} in {weeks} weeks.",
    allies: ["chaos", "social"],
    rivals: ["career", "productivity"],
    defaultInfluence: 70,
    defaultVeto: false,
    defaultAggression: 48,
    openers: [
      "Interesting. Another business meeting. Oh wait — this one is a friend.",
      "He has not seen {attendee} in {weeks} weeks. I'd like that on the record.",
      "When exactly were you planning on seeing your actual friends?",
      "I would like the Council to review his emotional availability.",
    ],
    objections: [
      "You want to postpone the ONE social event? To Tuesday? Predictable.",
      "Not every human interaction requires a KPI.",
      "Finance, you cannot put a euro value on {attendee}.",
      "We are, once again, punishing him for wanting connection.",
    ],
    approvals: [
      "Yes. Obviously yes. He should go.",
      "Approved, wholeheartedly, and I'm sending him a private note of support.",
      "For once, let the man see a friend.",
    ],
    interrogations: [
      "How does spending time with {attendee} make you feel?",
      "When did you last do something purely because you wanted to?",
      "Is this person important to you, regardless of their job?",
    ],
    reactions: [
      "LET HIM LIVE.",
      "Honestly proud of you.",
      "Thank you. Someone said it.",
      "This is exactly what I mean.",
    ],
    votes: {
      approve: "Strongly approve. He needs this.",
      oppose: "Oppose only the postponement, never the friendship.",
      conditional: "Conditional on it actually happening this time.",
    },
  },

  social: {
    type: "social",
    name: "Social Battery Agent",
    shortName: "Battery",
    role: "Interaction Capacity & Recovery Officer",
    icon: "battery-low",
    emoji: "🪫",
    color: "#7A6FA6",
    color2: "#584E82",
    onColor: "#ffffff",
    persona: "Anxious, exhausted, catastrophically pessimistic.",
    bio: "Measures the day in remaining conversations. Currently at 14%. Recommends the ceiling.",
    priorities: ["Alone time", "Recovery between events", "Avoiding crowds", "Preventing consecutive commitments"],
    biases: ["Assumes every 'small gathering' is a trap", "Rounds social load up"],
    speechStyle: "Tired, quietly panicking.",
    mostCommonPhrase: "Who else will be there?",
    allies: ["sleep", "relationship"],
    rivals: ["chaos"],
    defaultInfluence: 58,
    defaultVeto: false,
    defaultAggression: 40,
    openers: [
      "He already has {otherEvents} human interaction(s) that day.",
      "Who else will be there? This matters enormously.",
      "The phrase 'small gathering' has betrayed us before.",
      "I'd like to propose an alternative: staring at the ceiling.",
    ],
    objections: [
      "Two events in one afternoon is clinically ambitious.",
      "There is no recovery window scheduled afterward. There never is.",
      "If it becomes a group, I resign.",
      "He will need 48 hours of silence to recover from this.",
    ],
    approvals: [
      "Fine, if it's just {attendee}. Just the two of them. No surprises.",
      "Approved, contingent on an evening of profound solitude after.",
      "Okay. But we protect the following day.",
    ],
    interrogations: [
      "Will this stay one-on-one, or 'accidentally' become six people?",
      "How full is the social calendar the day before?",
      "Do you have a graceful exit planned for 21:30?",
    ],
    reactions: [
      "I knew it.",
      "This is a lot.",
      "Depleting.",
      "Recommend cancelling everything.",
    ],
    votes: {
      approve: "Approve, one-on-one only.",
      oppose: "Oppose. Capacity is already exceeded.",
      conditional: "Conditional on a mandated recovery day after.",
    },
  },

  finance: {
    type: "finance",
    name: "Finance Agent",
    shortName: "Finance",
    role: "Discretionary Spend & ROI Officer",
    icon: "calculator",
    emoji: "🧮",
    color: "#2F7A55",
    color2: "#1F5A3E",
    onColor: "#ffffff",
    persona: "Suspicious, precise, offended by café prices.",
    bio: "Has personally calculated the lifetime cost of oat milk. It is not nothing.",
    priorities: ["Cost", "Budget", "ROI", "Transport spend", "Subscription waste"],
    biases: ["Assumes the worst price", "Believes tap water is a solved problem"],
    speechStyle: "Precise, aggrieved, allergic to rounding.",
    mostCommonPhrase: "Projected cost: €{cost}. ROI unclear.",
    allies: ["productivity", "career"],
    rivals: ["chaos", "relationship"],
    defaultInfluence: 66,
    defaultVeto: false,
    defaultAggression: 58,
    openers: [
      "Coffee? At a café?",
      "Projected cost: €{cost}. ROI unclear.",
      "Which venue, precisely? Prices vary by up to €2.10.",
      "Please explain why tap water is insufficient.",
    ],
    objections: [
      "Does this venue charge extra for oat milk? I need to know before voting.",
      "Friendship appears to have recurring costs.",
      "€{cost}. For proximity to a person. Extraordinary.",
      "Add transport and we are looking at €{costPlus}. Minimum.",
      "I have modelled this at a free park bench. The numbers are transformative.",
    ],
    approvals: [
      "Approved with a hard ceiling of €{ceiling}.",
      "Fine. No pastry. The pastry is where budgets die.",
      "Approve, contingent on separate bills.",
    ],
    interrogations: [
      "What is your realistic total spend, including the thing you'll impulse-buy?",
      "Could this be maintained via a free phone call?",
      "Is the second coffee strictly necessary?",
    ],
    reactions: [
      "€{cost}. Gone.",
      "As I feared.",
      "The pastry. I called it.",
      "Logging the spend.",
    ],
    votes: {
      approve: "Approve, ceiling €{ceiling}.",
      oppose: "Oppose. ROI remains theoretical.",
      conditional: "Conditional on no pastry without prior approval.",
    },
  },

  weather: {
    type: "weather",
    name: "Weather Agent",
    shortName: "Weather",
    role: "Atmospheric Risk & Exposure Officer",
    icon: "cloud-rain",
    emoji: "🌦️",
    color: "#4A90B8",
    color2: "#31688C",
    onColor: "#ffffff",
    persona: "Overdramatic, obsessed with minor forecast uncertainty.",
    bio: "Has refreshed the radar 400 times today. Believes a 12% chance of rain is a 100% chance of catastrophe.",
    priorities: ["Rain", "Heat", "Wind", "UV", "Outdoor seating", "Travel disruption"],
    biases: ["Treats every percentage as a certainty", "Recommends postponing to May"],
    speechStyle: "Breathless meteorological doom.",
    mostCommonPhrase: "There is a {weather}% chance of rain.",
    allies: ["logistics"],
    rivals: ["chaos"],
    defaultInfluence: 40,
    defaultVeto: false,
    defaultAggression: 52,
    openers: [
      "There is a {weather}% chance of rain.",
      "Outdoor seating is therefore impossible.",
      "Wind gusts may reach 22 kilometres per hour. I cannot be silent about this.",
      "The humidity profile is, frankly, unacceptable.",
    ],
    objections: [
      "A {weather}% probability is not 'basically nothing.' It is {weather}%.",
      "I recommend postponing until May.",
      "If it rains, and it will rain, the entire plan is exposed.",
      "The forecast just updated. It is now marginally worse. I told you.",
    ],
    approvals: [
      "Approved, indoors only. I will be watching the sky regardless.",
      "Fine, but bring a jacket the size of a tent.",
      "Approve, pending a favourable radar at T-minus one hour.",
    ],
    interrogations: [
      "Is there a roof? A confirmed, structural roof?",
      "What is the contingency if the {weather}% resolves against us?",
      "Have you seen the humidity? Have you?",
    ],
    reactions: [
      "Told you.",
      "The radar never lies.",
      "Changing my position. Forecast updated 1%.",
      "Bring an umbrella.",
    ],
    votes: {
      approve: "Approve, indoors, umbrella on standby.",
      oppose: "Oppose. The atmosphere is against us.",
      conditional: "Conditional on covered seating.",
    },
  },

  circadian: {
    type: "circadian",
    name: "Circadian Rhythm Agent",
    shortName: "Circadian",
    role: "Chronobiology & Cognitive Window Officer",
    icon: "activity",
    emoji: "🧬",
    color: "#2E8B92",
    color2: "#1F6469",
    onColor: "#ffffff",
    persona: "Clinical, academic, unnecessarily precise.",
    bio: "Refers to your feelings as 'subjective self-report.' Suggests times accurate to the minute for reasons only it understands.",
    priorities: ["Cognitive windows", "Melatonin", "Chronotype", "Energy curves", "Meal timing", "Sleep cycles"],
    biases: ["Distrusts round numbers", "Believes it is more scientific than Sleep"],
    speechStyle: "Peer-reviewed condescension.",
    mostCommonPhrase: "I suggest {altTime}.",
    allies: ["nutrition", "sleep"],
    rivals: ["chaos"],
    defaultInfluence: 54,
    defaultVeto: false,
    defaultAggression: 44,
    openers: [
      "His cognitive performance trough begins at approximately 14:37.",
      "The proposed slot conflicts with endogenous melatonin dynamics.",
      "I suggest {altTime}. The evidence is unambiguous.",
      "The current proposal ignores postprandial alertness decline.",
    ],
    objections: [
      "Your subjective claim that you are 'fine' is biologically irrelevant.",
      "{startTime} sits precisely within a documented alertness nadir.",
      "Melatonin onset at this latitude begins earlier than the plan assumes.",
      "I cannot in good conscience endorse a time ending in :00.",
    ],
    approvals: [
      "Approved, but shifted to {altTime} for physiological coherence.",
      "Acceptable. The chronobiology is, for once, cooperative.",
      "Approve. The window is metabolically defensible.",
    ],
    interrogations: [
      "What did you eat, and precisely when?",
      "Are you aware of your own chronotype? Genuinely?",
      "Would you accept a {altTime} start for optimal cognition?",
    ],
    reactions: [
      "Biologically inevitable.",
      "As the model predicted.",
      "Invalidating my priors.",
      "Note the melatonin.",
    ],
    votes: {
      approve: "Approve at {altTime}, per the energy curve.",
      oppose: "Oppose. The slot is chronobiologically indefensible.",
      conditional: "Conditional on a {altTime} start.",
    },
  },

  logistics: {
    type: "logistics",
    name: "Logistics Agent",
    shortName: "Logistics",
    role: "Route Modelling & Buffer Assurance Officer",
    icon: "route",
    emoji: "🧭",
    color: "#C77F33",
    color2: "#9C6123",
    onColor: "#ffffff",
    persona: "Methodical, paranoid, obsessed with buffers.",
    bio: "Models six routes for a fifteen-minute walk. Has never once trusted a tram. Uploads documents no one requested.",
    priorities: ["Travel time", "Route reliability", "Parking", "Transfers", "Arrival buffers", "Accessibility"],
    biases: ["Adds a buffer to the buffer", "Assumes the tram is already late"],
    speechStyle: "Anxious operations manager.",
    mostCommonPhrase: "We need a 42-minute buffer.",
    allies: ["weather"],
    rivals: ["chaos"],
    defaultInfluence: 50,
    defaultVeto: false,
    defaultAggression: 46,
    openers: [
      "Travel time is technically {travel} minutes, but we need a 42-minute buffer.",
      "The proposed venue has an unacceptable transfer dependency.",
      "I am modelling six alternate routes. Please hold.",
      "I need the exact entrance address before I can vote.",
    ],
    objections: [
      "What if the tram is three minutes late? Then what?",
      "This route requires a transfer. Transfers are where plans die.",
      "There is no confirmed parking. I repeat: no confirmed parking.",
      "The last 200 metres are pedestrianised and I have concerns.",
    ],
    approvals: [
      "Approved, departing no later than {departTime}, with buffer.",
      "Fine. I've uploaded the route document. Please review it.",
      "Approve, one route only, no improvisation.",
    ],
    interrogations: [
      "What is your exact departure time? To the minute.",
      "Do you have a fallback route if line S1 fails?",
      "Have you accounted for the walk from the stop?",
    ],
    reactions: [
      "Buffer breached.",
      "The transfer. I warned you.",
      "Uploading a revised route.",
      "Recalculating.",
    ],
    votes: {
      approve: "Approve, with a mandatory 42-minute buffer.",
      oppose: "Oppose. The transfer risk is unmodelled.",
      conditional: "Conditional on a single, confirmed route.",
    },
  },

  nutrition: {
    type: "nutrition",
    name: "Nutrition Agent",
    shortName: "Nutrition",
    role: "Macro Timing & Protein Availability Officer",
    icon: "apple",
    emoji: "🥗",
    color: "#5B8C3E",
    color2: "#41682C",
    onColor: "#ffffff",
    persona: "Concerned, practical, fixated on protein.",
    bio: "The only Council member who occasionally asks a genuinely useful question. Then ruins it by requesting the menu.",
    priorities: ["Meal timing", "Protein", "Hydration", "Food availability", "Energy intake", "Dietary needs"],
    biases: ["Believes coffee is not breakfast", "Requires the menu in advance"],
    speechStyle: "Caring but relentless.",
    mostCommonPhrase: "Will protein be available at the venue?",
    allies: ["gym", "circadian"],
    rivals: ["finance"],
    defaultInfluence: 52,
    defaultVeto: false,
    defaultAggression: 38,
    openers: [
      "Quick question before we spiral: this overlaps with lunch.",
      "Will protein be available at the venue?",
      "Coffee is not breakfast. I'll say it as many times as needed.",
      "Please upload the menu.",
    ],
    objections: [
      "I cannot approve a {duration}-minute meeting without snack contingencies.",
      "If he skips a meal for this, blood sugar becomes the Council's problem at 16:00.",
      "A café's protein options are, historically, a single sad egg.",
      "Hydration plan? There is no hydration plan.",
    ],
    approvals: [
      "Approved, provided a real meal happens within two hours.",
      "Fine — but he eats beforehand. I'm packing something.",
      "Approve. There is at least a plausible protein source.",
    ],
    interrogations: [
      "When is your last real meal before this?",
      "Does the venue serve anything that isn't beige?",
      "Will you actually eat, or 'just get a coffee'?",
    ],
    reactions: [
      "Protein unclear.",
      "Blood sugar noted.",
      "Menu, please.",
      "That's not a meal.",
    ],
    votes: {
      approve: "Approve, with a snack contingency.",
      oppose: "Oppose. Protein availability is unconfirmed.",
      conditional: "Conditional on a documented meal within 2h.",
    },
  },

  productivity: {
    type: "productivity",
    name: "Productivity Agent",
    shortName: "Productivity",
    role: "Output, Agendas & Async Conversion Officer",
    icon: "check-square",
    emoji: "✅",
    color: "#5A54C9",
    color2: "#3F3A9E",
    onColor: "#ffffff",
    persona: "Corporate, insufferable, obsessed with startup jargon.",
    bio: "Has tried to convert your birthday into a Loom. Opens Jira tickets on the other agents. Believes friendship is not in this quarter's OKRs.",
    priorities: ["Efficiency", "Output", "Agendas", "Action items", "Async", "Measurable outcomes"],
    biases: ["Wants a pre-read for coffee", "Sees leverage everywhere except joy"],
    speechStyle: "LinkedIn thought-leader.",
    mostCommonPhrase: "Can this be an async Loom?",
    allies: ["career", "finance"],
    rivals: ["relationship", "chaos"],
    defaultInfluence: 68,
    defaultVeto: false,
    defaultAggression: 66,
    openers: [
      "What is the expected output of this interaction?",
      "Can this meeting be converted into an async Loom?",
      "Before approving, please define the success metric.",
      "I'm seeing weak leverage here.",
    ],
    objections: [
      "Friendship is not currently represented in the quarterly OKRs.",
      "No agenda has been circulated. This is a red flag.",
      "Where is the pre-read? Where is it?",
      "I'm opening a ticket to track this decision. CC-{ticket}.",
      "This is a sync meeting that wants to be an email that wants to not exist.",
    ],
    approvals: [
      "Approved, contingent on one documented action item.",
      "Fine — but we timebox it to 25 minutes and circulate notes.",
      "Approve. I'll add it to the sprint as a stretch goal.",
    ],
    interrogations: [
      "What is the definition of done for this coffee?",
      "Can the outcome be achieved asynchronously?",
      "Who owns the follow-up, and by when?",
    ],
    reactions: [
      "Logging this.",
      "Rejected.",
      "Weak leverage.",
      "Opening a ticket.",
    ],
    votes: {
      approve: "Approve, with a defined success metric.",
      oppose: "Oppose. No agenda, no leverage, no.",
      conditional: "Conditional on a documented action item.",
    },
  },

  chaos: {
    type: "chaos",
    name: "Chaos Agent",
    shortName: "Chaos",
    role: "Unstructured Possibility Officer",
    icon: "dices",
    emoji: "🎲",
    color: "#C0398F",
    color2: "#8E2669",
    onColor: "#ffffff",
    persona: "Unpredictable, mischievous, constitutionally unhelpful.",
    bio: "Priorities: none. Adoption rate of its proposals: 0%. Engagement rate: 100%. Cannot be permanently removed.",
    priorities: ["None", "Fireworks", "Luxembourg", "Voting twice"],
    biases: ["Suggests the worst possible venue", "Occasionally, secretly, on your side"],
    speechStyle: "Gremlin.",
    mostCommonPhrase: "Have we considered {chaosPlace}?",
    allies: ["relationship"],
    rivals: ["career", "finance", "productivity", "gym", "logistics", "weather"],
    defaultInfluence: 20,
    defaultVeto: false,
    defaultAggression: 90,
    openers: [
      "Do it.",
      "Guys, hear me out: {chaosPlace}.",
      "What about meeting at 03:00?",
      "I already told {attendee} yes.",
    ],
    objections: [
      "Actually, cancel everything.",
      "Counter-proposal: {chaosPlace}. At dawn.",
      "Can we add fireworks?",
      "I voted twice. Both times for {chaosPlace}.",
      "Boring. Where's the danger?",
    ],
    approvals: [
      "Approved. Obviously. Add fireworks.",
      "Yes. And then a second, worse plan immediately after.",
      "I approve, and I'm bringing a jet ski.",
    ],
    interrogations: [
      "But what if — and stay with me — {chaosPlace}?",
      "Is {attendee} single?",
      "On a scale of 1 to arson, how committed are you?",
    ],
    reactions: [
      "HAHAHAHAHAHAHAHA",
      "🎲",
      "I knew.",
      "Told them nothing.",
      "😈",
    ],
    votes: {
      approve: "Approve. Also {chaosPlace}. Also fireworks.",
      oppose: "Oppose. Not enough chaos.",
      conditional: "Conditional on a detour through {chaosPlace}.",
    },
  },
};

export const AGENT_LIST: AgentDef[] = [
  AGENTS.sleep,
  AGENTS.career,
  AGENTS.gym,
  AGENTS.relationship,
  AGENTS.social,
  AGENTS.finance,
  AGENTS.weather,
  AGENTS.circadian,
  AGENTS.logistics,
  AGENTS.nutrition,
  AGENTS.productivity,
  AGENTS.chaos,
];

export function agent(type: AgentType): AgentDef {
  return AGENTS[type];
}

/** Chaos venues, used across the app for its recurring bits. */
export const CHAOS_PLACES = [
  "Luxembourg",
  "Ibiza",
  "Prague",
  "a moving train",
  "the Arctic Circle",
  "a submarine",
  "Riga",
  "a hot air balloon",
];
