<?php
require __DIR__ . '/inc.php';
$db = db();
$id = (int)($_GET['id'] ?? 0);
$st = $db->prepare("SELECT * FROM models WHERE id=?");
$st->execute([$id]);
$m = $st->fetch(PDO::FETCH_ASSOC);
if (!$m) { page_header('404 - The Weight Bay', true); echo '<h1 align="center">Model walked the plank (404)</h1>'; page_footer(); exit; }

[$se, $le] = swarm($m['hf_id'], (int)$m['downloads']);
$cs = $db->prepare("SELECT * FROM comments WHERE model_id=? ORDER BY posted_at DESC");
$cs->execute([$id]);
$comments = $cs->fetchAll(PDO::FETCH_ASSOC);

page_header($m['name'] . " (download safetensors) - The Weight Bay", true);
search_box();
?>
<table width="100%" cellpadding="8"><tr><td>
<font size="4"><b><?= h($m['name']) ?></b></font>
<?php if ($m['vip']): ?>&nbsp;<span class="vip">💀 VIP</span> <font size="1" color="#00aa00">(Trusted uploader — a literal Fortune 500 legal department)</font><?php endif; ?>
<table width="100%" cellpadding="4"><tr>
<td valign="top" width="55%">
<table cellpadding="2" style="font-size:11px">
<tr><td><b>Type:</b></td><td><a href="browse.php?cat=<?= $m['cat'] ?>"><?= h(CATS[$m['cat']] ?? '?') ?></a> &gt; <?= h($m['pipeline_tag']) ?></td></tr>
<tr><td><b>Files:</b></td><td>1 (we refuse to count the tokenizer)</td></tr>
<tr><td><b>Size:</b></td><td><?= fmt_size($m['size_bytes'] ? (int)$m['size_bytes'] : null) ?></td></tr>
<tr><td><b>Uploaded:</b></td><td><?= h(str_replace('T', ' ', substr($m['last_modified'], 0, 16))) ?> GMT</td></tr>
<tr><td><b>ULed by:</b></td><td><b><?= h($m['author']) ?></b></td></tr>
<tr><td><b>License:</b></td><td><?= h($m['license']) ?> <font color="#888">(yes, there's a license. on a "pirate" site. we know.)</font></td></tr>
<tr><td><b>Downloads:</b></td><td><?= fmt_n((int)$m['downloads']) ?> <font color="#888">(real number, from the real API)</font></td></tr>
<tr><td><b>Seeders:</b></td><td><font color="#00aa00"><b><?= fmt_n($se) ?></b></font> <font color="#888">(fake, fluctuates live for ambience)</font></td></tr>
<tr><td><b>Leechers:</b></td><td><font color="#aa0000"><?= fmt_n($le) ?></font></td></tr>
<tr><td><b>Info hash:</b></td><td><font face="Courier New" size="1"><?= fake_infohash($m['hf_id']) ?></font></td></tr>
</table>
<br>
<a href="<?= h(magnet($m)) ?>" style="font-size:15px;font-weight:bold">🧲 GET THIS MAGNET LINK</a>
<font size="1" color="#888">(points at a swarm of exactly zero peers)</font><br><br>
<a href="download.php?id=<?= $m['id'] ?>" onclick="return confirm('⚠ WARNING ⚠\n\nYou are about to download something 100% LEGAL.\n\nNo VPN needed. No letter from a lawyer. Nothing.\nThe thrill you are feeling is artificial.\n\nProceed anyway?')"
   style="font-size:15px;font-weight:bold;background:#ffcc00;border:3px outset #aa8800;padding:4px 10px;color:#000;text-decoration:none">
💾 DOWNLOAD .TORRENT</a><br><br>
<font size="1" color="#888">(it is not a torrent. click it. trust us. we are a website with a skull on it.)</font>
</td>
<td valign="top">
<?php render_ad(); ?>
<div style="border:1px dashed #888;background:#000;color:#0f0;font-family:'Courier New',monospace;font-size:10px;padding:8px;white-space:pre">
        ⛵ THE WEIGHT BAY presents ⛵
  ═══════════════════════════════════════
   <?= h(strtoupper($m['name'])) . "\n" ?>
  ═══════════════════════════════════════
   SUPPLiER..: <?= h($m['author']) . "\n" ?>
   FORMAT....: safetensors (no pickle, no problem)
   PROTECTiON: none. it's open weights.
   CRACKED BY: nobody. it was never locked.
   iNSTALL...: pip install transformers
   GREETZ....: to every uploader seeding
               from a Fortune 500 datacenter
  ═══════════════════════════════════════
   remember: SEED your gradients
</div>
</td>
</tr></table>
</td></tr></table>

<table width="100%" cellpadding="8"><tr><td>
<font size="3"><b>Comments (<?= count($comments) ?>)</b></font>
<font size="1" color="#888">— pre-generated by an AI, about AI models, on a fake tracker. it's slop all the way down</font>
<?php foreach ($comments as $c): ?>
<div class="comment">
<span class="chead"><b><?= h($c['username']) ?></b> at <?= h($c['posted_at']) ?>:</span><br>
<?= h($c['body']) ?>
</div>
<?php endforeach; ?>
<form onsubmit="alert('Your comment was thrown into /dev/null with full honors.\n(This site is read-only, like all good archives.)'); return false">
<textarea rows="3" cols="70" style="font-family:'Comic Sans MS'"></textarea><br>
<input type="submit" value="Post comment (into the void)">
</form>
</td></tr></table>
<?php page_footer(); ?>
