import type { AgentType, AgentState, Beat, MeetingRequest } from "@/lib/types";
import { MockDirector, type DirectorOptions } from "./mock";
import {
  correctiveResponse,
  incidentAfterAnswer,
  incidentOpening,
  isIncidentTrigger,
} from "./incident";

export type EngineMode = "mock" | "llm";

/**
 * The store talks to a NegotiationEngine. Both engines return the same "beat"
 * stream, so the UI is identical whether comedy is generated by the local
 * deterministic director (default, no API key) or by a real LLM orchestrator.
 */
export interface NegotiationEngine {
  mode: EngineMode;
  vars: Record<string, string | number | undefined>;
  opening(): Promise<Beat[]>;
  afterAnswer(answer: string): Promise<Beat[]>;
  onDecision(action: "accept" | "appeal" | "ignore" | "modify"): Promise<Beat[]>;
  incidentOpening(): Promise<Beat[]>;
  incidentAfterAnswer(answer: string): Promise<Beat[]>;
  correctiveResponse(action: "accept" | "appeal" | "rebel"): Promise<Beat[]>;
}

// ---------------------------------------------------------------------------
// Mock engine — the default. Fully deterministic, zero network, zero keys.
// ---------------------------------------------------------------------------
export class MockEngine implements NegotiationEngine {
  mode: EngineMode = "mock";
  director: MockDirector;

  constructor(request: MeetingRequest, opts?: DirectorOptions) {
    this.director = new MockDirector(request, opts);
  }
  get vars() {
    return this.director.vars;
  }
  async opening() {
    return this.director.opening();
  }
  async afterAnswer(answer: string) {
    return this.director.afterAnswer(answer);
  }
  async onDecision(action: "accept" | "appeal" | "ignore" | "modify") {
    return this.director.onDecision(action);
  }
  async incidentOpening() {
    return incidentOpening(this.director.vars, this.director.rng);
  }
  async incidentAfterAnswer(answer: string) {
    return incidentAfterAnswer(answer, this.director.vars, this.director.rng);
  }
  async correctiveResponse(action: "accept" | "appeal" | "rebel") {
    return correctiveResponse(action, this.director.vars, this.director.rng);
  }
}

// ---------------------------------------------------------------------------
// LLM engine — optional. Calls a server orchestrator; falls back to mock on
// ANY error so the live demo can never break because of an API.
// ---------------------------------------------------------------------------
export class LlmEngine implements NegotiationEngine {
  mode: EngineMode = "llm";
  private fallback: MockEngine;

  constructor(
    private request: MeetingRequest,
    private opts?: DirectorOptions,
  ) {
    this.fallback = new MockEngine(request, opts);
  }
  get vars() {
    return this.fallback.vars;
  }

  private async call(step: string, payload: Record<string, unknown>): Promise<Beat[]> {
    try {
      const res = await fetch("/api/orchestrate", {
        method: "POST",
        headers: { "content-type": "application/json" },
        body: JSON.stringify({ step, request: this.request, ...payload }),
      });
      if (!res.ok) throw new Error("orchestrator http " + res.status);
      const data = (await res.json()) as { beats?: Beat[] };
      if (!data.beats || !data.beats.length) throw new Error("empty beats");
      return data.beats;
    } catch {
      // Reliable fallback — the Council always convenes.
      return this.fallbackFor(step, payload);
    }
  }

  private fallbackFor(step: string, payload: Record<string, unknown>): Promise<Beat[]> {
    switch (step) {
      case "opening":
        return this.fallback.opening();
      case "afterAnswer":
        return this.fallback.afterAnswer(String(payload.answer ?? ""));
      case "onDecision":
        return this.fallback.onDecision(payload.action as any);
      case "incidentOpening":
        return this.fallback.incidentOpening();
      case "incidentAfterAnswer":
        return this.fallback.incidentAfterAnswer(String(payload.answer ?? ""));
      case "correctiveResponse":
        return this.fallback.correctiveResponse(payload.action as any);
      default:
        return this.fallback.opening();
    }
  }

  async opening() {
    return this.call("opening", {});
  }
  async afterAnswer(answer: string) {
    return this.call("afterAnswer", { answer });
  }
  async onDecision(action: "accept" | "appeal" | "ignore" | "modify") {
    return this.call("onDecision", { action });
  }
  async incidentOpening() {
    return this.call("incidentOpening", {});
  }
  async incidentAfterAnswer(answer: string) {
    return this.call("incidentAfterAnswer", { answer });
  }
  async correctiveResponse(action: "accept" | "appeal" | "rebel") {
    return this.call("correctiveResponse", { action });
  }
}

export function createEngine(
  request: MeetingRequest,
  opts?: DirectorOptions & { mode?: EngineMode },
): NegotiationEngine {
  if (opts?.mode === "llm") return new LlmEngine(request, opts);
  return new MockEngine(request, opts);
}

export { isIncidentTrigger };

// ---- Orchestrator contract (for the optional real-LLM implementation) ----
// One call generates several messages while preserving the illusion of 12
// independent agents. See /api/orchestrate.
export interface OrchestratorInput {
  request: MeetingRequest;
  step: string;
  phase?: string;
  consensus?: number;
  agentStates?: AgentState[];
  openObjections?: string[];
  previousMessages?: { agent?: AgentType; sender: string; body: string }[];
  userResponse?: string;
  comedy?: "dry" | "balanced" | "unhinged";
}
export interface OrchestratorOutput {
  beats: Beat[];
}
